services:
  e2e:
    image: comses/cypress
    build: e2e
    environment:
      - CYPRESS_baseUrl=http://server:8000
    volumes:
      - ./e2e/cypress:/code/cypress
    depends_on:
      server:
        condition: service_healthy
  vite:
    volumes:
      - ./frontend:/code
    command: ["npm", "run", "build"]
    environment:
      NODE_ENV: "e2e"
  server:
    image: comses/server:dev
    volumes:
      - ./django:/code
      - ./docs:/docs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.e2e"
    ports:
      - "127.0.0.1:8000:8000"
