name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENVIRONMENT: test
    steps:
      - uses: actions/checkout@v4
      - name: build containers and run Django tests
        run: make test
