name: CoMSES Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: install coveralls and coverage
      run: |
        python -m pip install --upgrade pip
        pip3 install coveralls coverage
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v2
    - name: build containers and run Django tests
      run: make test

    - name: run cypress integration tests
      uses: cypress-io/github-action@v5
      with:
        start: yarn test
        wait-on: 'http://localhost:8000, http://localhost:5000'
        working-directory: cypress
