name: E2E Tests

on:
  # workflow_dispatch # disabled pending db seeding
  push:
    branches: [ main, test-e2e ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build containers and run cypress e2e tests
        # TODO: seed the database with a sparse(r) dump so there are pages to test..
        run: make e2e

      - name: upload artifacts
        if: failure() # only store recordings if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: e2e/cypress/videos/
