name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: deploy services in e2e mode
        run: make e2e

      - name: run e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
          wait-on: "http://localhost:8000"
          wait-on-timeout: 300

      - name: display service logs
        if: failure()
        run: docker compose -f docker-compose.yml -f e2e.yml logs

      - name: upload cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: e2e/cypress/videos
